### ISSUE TITLE
Centerstage game released. Will the field and game be updated?

### ISSUE THREAD

**Issue by Karthick-Govindaraj007** [Beta8397/virtual_robot#100]
Will the game and field be updated for centerstage?

**Comment by jkenney2** [comment]
The field was updated the day the game was released. As to game elements: probably won’t add pixels, but will look at setting things up so the robot can’t just drive over the backdrops and A-frames.

**Comment by Karthick-Govindaraj007** [comment]
Oh, ok! Thank you!
