### ISSUE TITLE
Recent Feature Changes

### ISSUE THREAD

**Issue by jkenney2** [Beta8397/virtual_robot#14]
@alan412 @c4glenn 

Thanks for your contributions! If you clone or download the repository, you'll find they (regular OpMode capability, ftc16072 example op modes, gamepad deadzone) are incorporated, and that there have been a couple of additional significant changes: 

1. The app now allows the use of two gamepads (just use Start-A and Start-B as you would for FTC SDK).

2. OpModes are now registered in the same way the FTC SDK does it, using TeleOp, Autonomous, and Disabled annotations. The OpModes class and OpModeList are gone. In theory, you should be able to put your op modes in any package, not just teamcode.

**Comment by alan412** [comment]
New master looks great!   (As you can tell, we are using it as a rookie team and it is very helpful for us debugging)
