### ISSUE TITLE
Should support opMode

### ISSUE THREAD

**Issue by alan412** [Beta8397/virtual_robot#4]
OpModes (that aren't linear) should be the main support.   LinearOpModes are simply a derived class from OpMode, so bringing over that declaration would allow both OpModes and LinearOpModes to be supported.   

I forked the project so I could see about adding this support.   If I am able to get to it, then I'll issue a pull request.

**Comment by jkenney2** [comment]
Thanks,
Have merged pull request into a new branch for testing before merging into master branch.

**Comment by jkenney2** [comment]
Tweaks made so that linear op modes will terminate normally when runOpMode exits, and to make telemetry updates automatic when looping in regular op mode. Merged with master. Thanks for your contribution! A great addition for teams that like to use regular op modes.
