### ISSUE TITLE
Telemetry behavior needs to follow FTC SDK more closely

### ISSUE THREAD

**Issue by jkenney2** [Beta8397/virtual_robot#40]
@alan412 

Currently, update() statement ALWAYS clears telemetry. That means that telemetry written during init() method doesn't persist. It gets cleared immediately by the call to telemetry.update() in the internalPostInitLoop() method.

For example, this breaks the Helloworld example in Learn Java For FTC.

I will do a little testing with the real SDK and Android Studio to figure out how this behaves, and make some changes.

**Comment by jkenney2** [comment]
The appropriate behavior seems to be:

1. If there has been a call to telemetry.addData since the last update, then telemetry.update() will clear existing telemetry, then write new telemetry.

2. If there has not been a call to telemetry.addData since the last update, then telemetry.update() does nothing.

**Comment by alan412** [comment]
I believe that to be correct.

**Comment by jkenney2** [comment]
Fixed.
