### ISSUE TITLE
Consider adding Amazon Corretto to JDK options

### ISSUE THREAD

**Issue by alan412** [Beta8397/virtual_robot#42]
As Oracle is making it more and more of a pain with what has to be agreed to to download the jdk 8, I am having students get Amazon Corretto (their JDK 8).    I have verified it works with the simulator.

To get it: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

**Comment by jkenney2** [comment]
That's great. I hadn't heard of Corretto. I modified the Detailed Installation Instructions to include that as an option.
