### ISSUE TITLE
Add Differential swerve

### ISSUE THREAD

**Issue by adamrubinfeld** [Beta8397/virtual_robot#52]
Hi
It's not issue it's suggestion
I think you need to add swerve and Differential swerve it's can be very helpful for team I mentor (I make one on yours sim but it's not working so good)
I can help if you want

**Comment by jkenney2** [comment]
I'll look into it. A couple of questions for you:
1. What's the difference between a swerve and a differential swerve?
2. What do you use to steer each wheel, servo or motor?

**Comment by adamrubinfeld** [comment]
The different is the diff swerve is have more torque beacuse you combine two motors to control the velocity and the module heading
For standard swerve on ftc you use CR and DC motor for each module and the torque is less then the diff swerve 
In diff swerve the software is harder beacuse you need to calculate the ratio between two motors on each module to set the module at the wanted angle 

I work with two teams on diff swerve and with one team I work on standard swerve I can say 100% for FTC diff swerve is better but again the software is very hard against the standard swerve

**Comment by jkenney2** [comment]
If you use crservo to steer a swerve, do you need to add an encoder to each pod, so you can tell what it's orientation is at any moment?

**Comment by adamrubinfeld** [comment]
You need to add encoder just for standard swerve with CR if it's with DC motor you don't need

For diff swerve you don't need at all

**Comment by jkenney2** [comment]
@adamrubinfeld 
Started a "swerve" branch that you can check out. At this point just a swerve drive, along with a TestSwerve op mode. The op mode is very crude at this point. Will work on this, and eventually try a differential swerve.

**Comment by adamrubinfeld** [comment]
Ok tnx
To do module rotation with continuous servo?

**Comment by adamrubinfeld** [comment]
i saw somone else work on a brench called swerve so i will give him to do that

**Comment by jkenney2** [comment]
@adamrubinfeld TestSwerve opmode re-written to demonstrate operation of a swerve drive with gamepad: left-stick for forward-reverse and left-right; right stick for turning. The details of the swerve drive control are in a separate class: SwerveDrive.java.
swerve branch merged into master.

**Comment by jkenney2** [comment]
@adamrubinfeld Added Differential Swerve Drive robot config, and test op mode.
