### ISSUE TITLE
Error When Inititializing

### ISSUE THREAD

**Issue by jackfetkovich** [Beta8397/virtual_robot#56]
When clicking the "init" button in the application window, the program throws:
"Exception from runOpMode:
java.lang.IllegalArgumentException
No com.qualcomm.robotcore.hardware.DcMotor named arm_motor is found.
Thread for runOpMode has terminated successfully."

As a result, driving does not work

**Comment by jkenney2** [comment]
@jackfetkovich The only robot configuration that has a motor named "arm_motor" is the ArmBot. Before running an op mode that uses a motor named arm_motor, you need to select the ArmBot robot configuration. Let me know whether this works.
